DROP TABLE IF EXISTS contributions;
CREATE TABLE contributions ( 
  id INTEGER NOT NULL,
  import_reference_id INTEGER,
  cycle INTEGER,
  transaction_namespace TEXT,
  transaction_id TEXT,
  transaction_type TEXT,
  filing_id TEXT,
  is_amendment TEXT,
  amount DECIMAL,
  date TEXT,
  contributor_name TEXT,
  contributor_ext_id TEXT,
  contributor_type TEXT,
  contributor_occupation TEXT,
  contributor_employer TEXT,
  contributor_gender TEXT,
  contributor_address TEXT,
  contributor_city TEXT,
  contributor_state TEXT,
  contributor_zipcode TEXT,
  contributor_category TEXT,
  organization_name TEXT,
  organization_ext_id TEXT,
  parent_organization_name TEXT,
  parent_organization_ext_id TEXT,
  recipient_name TEXT,
  recipient_ext_id TEXT,
  recipient_party TEXT,
  recipient_type TEXT,
  recipient_state TEXT,
  recipient_state_held TEXT,
  recipient_category TEXT,
  committee_name TEXT,
  committee_ext_id TEXT,
  committee_party TEXT,
  candidacy_status TEXT,
  district TEXT,
  district_held TEXT,
  seat TEXT,
  seat_held TEXT,
  seat_status TEXT,
  seat_result TEXT);

\COPY contributions FROM 'data/contributions.fec.csv' WITH CSV HEADER DELIMITER AS ',';
